# Site settings
title: "Brand Assets"
description: "Guidelines, assets and styles"

url: "https://lvuch.github.io/brand-guidelines/"
baseurl: "https://lvuch.github.io/brand-guidelines/"

# Build settings
markdown: kramdown
sass:
  sass_dir: _scss
  style: compressed